language: php

sudo: false

php:
  - '5.6'

cache:
  directories:
    - $HOME/.composer/cache  

install:
  - composer install --prefer-dist

script:
  - php vendor/bin/phpcs --standard=Zend --exclude=Generic.Files.LineLength app/code/
  - ./node_modules/.bin/grunt ci

